export const GET_INTERVENTIONS = 'GET_INTERVENTIONS';
export const GET_INTERVENTIONS_SUCCESS = 'GET_INTERVENTIONS_SUCCESS';
export const GET_INTERVENTIONS_FAILURE = 'GET_INTERVENTIONS_FAILURE';
export const SORT_INTERVENTIONS_BY_DATE = 'SORT_INTERVENTIONS_BY_DATE';

export const GET_INTERVENTION_BY_ID = 'GET_INTERVENTION_BY_ID';
export const GET_INTERVENTION_BY_ID_SUCCESS = 'GET_INTERVENTION_BY_ID_SUCCESS';
export const GET_INTERVENTION_BY_ID_FAILURE = 'GET_INTERVENTION_BY_ID_FAILURE';

export const ADD_INTERVENTION = 'ADD_INTERVENTION';
